#!/usr/bin/env bash

cript_dir=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)
dry="0"

while [[ $# > 0 ]]; do
    if [[ $1 == "--dry" ]]; then
        dry="1"
    fi
    shift

done

log() {
    if [[ $dry == "1" ]]; then
        echo "[DRY_RUN]: $@"
    else
        echo "@"
    fi
}

execute() {
    log "execute $@"
    if [[ $dry == "1" ]]; then
        return
    fi
    "$@"
}

log "---------------- dev-env ----------------"

copy_dir() {
    from=$1
    to=$2

    pushd $from >/dev/null
    dirs=$(find . -mindepth 1 -maxdepth 1 -type d -exec basename {} \;)
    for dir in $dirs; do
        execute rm -rf $to/$dir
        execute cp -r $dir $to/$dir
    done
    popd
}

copy_file() {
    from=$1
    to=$2
    name=$(basename $from)

    dirs=$(find . -mindepth 1 -maxdepth 1 -type d)
    execute rm $to/$name
    execute cp -r $from $to/$name
}

copy_dir env/.config $HOME/.config

